## Extract

In [16]:
import pandas as pd 
from datetime import datetime

df = pd.read_csv('D:\DIO\Bootcamp_Santander\contas_a_pagar.csv', dayfirst=True, parse_dates=['DT VENCIMENTO'], date_parser=lambda x: datetime.strptime(x, '%d/%m/%Y'))
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NOME           15 non-null     object
 1   VALOR          15 non-null     object
 2   DT VENCIMENTO  15 non-null     datetime64[ns]
 3   DT PAGAMENTO   6 non-null      object
dtypes: datetime64[ns](1), object(3)
memory usage: 612.0+ bytes

C:\Users\caduc\AppData\Local\Temp\ipykernel_10204\2371788018.py:4: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv('D:\DIO\Bootcamp_Santander\contas_a_pagar.csv', dayfirst=True, parse_dates=['DT VENCIMENTO'], date_parser=lambda x: datetime.strptime(x, '%d/%m/%Y'))

In [17]:
df

                              NOME        VALOR DT VENCIMENTO DT PAGAMENTO
0     Estrela do Norte Eletrônicos  R$ 9.084,00    2023-02-14   14/02/2023
1           Aroma de Café Boutique  R$ 3.619,00    2023-03-03   03/03/2023
2           Planeta dos Brinquedos  R$ 7.897,00    2023-04-21          NaN
3             Moda Elegante Outlet  R$ 6.925,00    2023-05-08   08/05/2023
4   Jardim das Flores Floricultura  R$ 1.618,00    2023-06-17          NaN
5                   TechVanguardia  R$ 1.779,00    2023-07-02          NaN
6        Delícias Caseiras Padaria  R$ 1.856,00    2023-08-29   29/08/2023
7           Esportes Radicais Gear  R$ 8.430,00    2023-09-12          NaN
8             Aconchego Decorações  R$ 1.964,00    2023-10-01          NaN
9                Livraria do Saber  R$ 2.374,00    2023-11-18          NaN
10            Cosmic Fashion Store  R$ 2.909,00    2023-12-07          NaN
11       Química e Cores Papelaria  R$ 5.140,00    2024-01-25          NaN
12        Gourmet Delights Mercado    R$ 945,00    2024-03-09   29/08/2023
13          Estilo Urbano Boutique  R$ 3.115,00    2024-04-27          NaN
14   Casa dos Animais de Estimação    R$ 420,00    2024-06-15   29/08/2023

## Transform

In [18]:
valor_sub = "Nao pago"
df = df.fillna(valor_sub)
df

                              NOME        VALOR DT VENCIMENTO DT PAGAMENTO
0     Estrela do Norte Eletrônicos  R$ 9.084,00    2023-02-14   14/02/2023
1           Aroma de Café Boutique  R$ 3.619,00    2023-03-03   03/03/2023
2           Planeta dos Brinquedos  R$ 7.897,00    2023-04-21     Nao pago
3             Moda Elegante Outlet  R$ 6.925,00    2023-05-08   08/05/2023
4   Jardim das Flores Floricultura  R$ 1.618,00    2023-06-17     Nao pago
5                   TechVanguardia  R$ 1.779,00    2023-07-02     Nao pago
6        Delícias Caseiras Padaria  R$ 1.856,00    2023-08-29   29/08/2023
7           Esportes Radicais Gear  R$ 8.430,00    2023-09-12     Nao pago
8             Aconchego Decorações  R$ 1.964,00    2023-10-01     Nao pago
9                Livraria do Saber  R$ 2.374,00    2023-11-18     Nao pago
10            Cosmic Fashion Store  R$ 2.909,00    2023-12-07     Nao pago
11       Química e Cores Papelaria  R$ 5.140,00    2024-01-25     Nao pago
12        Gourmet Delights Mercado    R$ 945,00    2024-03-09   29/08/2023
13          Estilo Urbano Boutique  R$ 3.115,00    2024-04-27     Nao pago
14   Casa dos Animais de Estimação    R$ 420,00    2024-06-15   29/08/2023

In [19]:


def pagoounão(lin):
    data_da_coluna = pd.to_datetime(lin['DT VENCIMENTO'])
    data_de_hoje = datetime.today().date()
    data_da_coluna_date = data_da_coluna.date()

    if 'Nao pago' in lin['DT PAGAMENTO'] and data_da_coluna_date < data_de_hoje:
        return 'Vencido'
    elif 'Nao pago' in lin['DT PAGAMENTO'] and data_da_coluna_date > data_de_hoje:
        return 'Pendente'
    else:
        return 'Pago'


df['STATUS'] = df.apply(pagoounão, axis=1)
df

,NOME,VALOR,DT VENCIMENTO,DT PAGAMENTO,STATUS
0,Estrela do Norte Eletrônicos,"R$ 9.084,00",2023-02-14,14/02/2023,Pago
1,Aroma de Café Boutique,"R$ 3.619,00",2023-03-03,03/03/2023,Pago
2,Planeta dos Brinquedos,"R$ 7.897,00",2023-04-21,Nao pago,Vencido
3,Moda Elegante Outlet,"R$ 6.925,00",2023-05-08,08/05/2023,Pago
4,Jardim das Flores Floricultura,"R$ 1.618,00",2023-06-17,Nao pago,Vencido
5,TechVanguardia,"R$ 1.779,00",2023-07-02,Nao pago,Vencido
6,Delícias Caseiras Padaria,"R$ 1.856,00",2023-08-29,29/08/2023,Pago
7,Esportes Radicais Gear,"R$ 8.430,00",2023-09-12,Nao pago,Pendente
8,Aconchego Decorações,"R$ 1.964,00",2023-10-01,Nao pago,Pendente
9,Livraria do Saber,"R$ 2.374,00",2023-11-18,Nao pago,Pendente
10,Cosmic Fashion Store,"R$ 2.909,00",2023-12-07,Nao pago,Pendente
11,Química e Cores Papelaria,"R$ 5.140,00",2024-01-25,Nao pago,Pendente
12,Gourmet Delights Mercado,"R$ 945,00",2024-03-09,29/08/2023,Pago
13,Estilo Urbano Boutique,"R$ 3.115,00",2024-04-27,Nao pago,Pendente
14,Casa dos Animais de Estimação,"R$ 420,00",2024-06-15,29/08/2023,Pago

In [20]:
def tempopend(lin):
    data_da_coluna = pd.to_datetime(lin['DT VENCIMENTO'])
    data_de_hoje = datetime.today().date()
    data_da_coluna_date = data_da_coluna.date()

    if 'Nao pago' in lin['DT PAGAMENTO'] and 'Vencido' in lin['STATUS']:
        return abs((data_de_hoje-data_da_coluna_date).days)
    else:
        return 'N/A'


df['DIAS VENCIDO'] = df.apply(tempopend, axis=1)
df

,NOME,VALOR,DT VENCIMENTO,DT PAGAMENTO,STATUS,DIAS VENCIDO
0,Estrela do Norte Eletrônicos,"R$ 9.084,00",2023-02-14,14/02/2023,Pago,N/A
1,Aroma de Café Boutique,"R$ 3.619,00",2023-03-03,03/03/2023,Pago,N/A
2,Planeta dos Brinquedos,"R$ 7.897,00",2023-04-21,Nao pago,Vencido,140
3,Moda Elegante Outlet,"R$ 6.925,00",2023-05-08,08/05/2023,Pago,N/A
4,Jardim das Flores Floricultura,"R$ 1.618,00",2023-06-17,Nao pago,Vencido,83
5,TechVanguardia,"R$ 1.779,00",2023-07-02,Nao pago,Vencido,68
6,Delícias Caseiras Padaria,"R$ 1.856,00",2023-08-29,29/08/2023,Pago,N/A
7,Esportes Radicais Gear,"R$ 8.430,00",2023-09-12,Nao pago,Pendente,N/A
8,Aconchego Decorações,"R$ 1.964,00",2023-10-01,Nao pago,Pendente,N/A
9,Livraria do Saber,"R$ 2.374,00",2023-11-18,Nao pago,Pendente,N/A
10,Cosmic Fashion Store,"R$ 2.909,00",2023-12-07,Nao pago,Pendente,N/A
11,Química e Cores Papelaria,"R$ 5.140,00",2024-01-25,Nao pago,Pendente,N/A
12,Gourmet Delights Mercado,"R$ 945,00",2024-03-09,29/08/2023,Pago,N/A
13,Estilo Urbano Boutique,"R$ 3.115,00",2024-04-27,Nao pago,Pendente,N/A
14,Casa dos Animais de Estimação,"R$ 420,00",2024-06-15,29/08/2023,Pago,N/A

## Load

In [24]:
df.to_csv('Analise_contas_final.xlsx', index=False)